function [IMUout, freq, Calidad] = f_cargashimmer(filename, dataLines)
%f_cargashimmer Import data from a std shimmer csv file
%  IMU = f_cargashimmer(filename, dataLines)
%  reads data for the specified row interval(s) of text file FILENAME.
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  maxfreqSession1ShimmerBFEDCalibratedSD1 = importfile("/Users/juan/Documents/MATLAB/maxfreq_Session1_ Calibrated_SD.csv", [4, Inf]);
%   or:
%  file='maxfreq_Session1_Shimmer_BFED_Calibrated_SD.csv';
%  medicion=f_cargashimmer(file);
%  See also READTABLE.
%
% Modified from Auto-generated by MATLAB on 07-May-2025 21:18:13

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [4, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Timestamp", "Acc_X", "Acc_Y", "Acc_Z", "Gyr_X", "Gyr_Y", "Gyr_Z", " Battery", "Mag_X", "Mag_Y", "Mag_Z", "VarName12"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "VarName12", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "VarName12", "EmptyFieldRule", "auto");

% Import the data
medicion = readtable(filename, opts);

% Convertimos los datos al formato std (tipo DOTS):
%

% tiempos en ms:
ts=(medicion.Timestamp-medicion.Timestamp(1));

%% Corrección de muestreos irregulares:
%
[ts_ext, IMU.Acc_X, idx_interp, huecos] = rellenarHuecosInterpolacion(ts, medicion.Acc_X, 1.6);
% signal=medicion.Acc_X;
% sig_ext=IMU.Acc_X;
% Calidad(1)=100*(1-(-size(signal)+size(sig_ext))/size(signal));
[ts_ext, IMU.Acc_Y, idx_interp, huecos] = rellenarHuecosInterpolacion(ts, medicion.Acc_Y, 1.6);
% signal=medicion.Acc_Y;
% sig_ext=IMU.Acc_Y;
% Calidad(2)=100*(1-(-size(signal)+size(sig_ext))/size(signal));
[ts_ext, IMU.Acc_Z, idx_interp, huecos] = rellenarHuecosInterpolacion(ts, medicion.Acc_Z, 1.6);
% signal=medicion.Acc_Z;
% sig_ext=IMU.Acc_Z;
% Calidad(3)=100*(1-(-size(signal)+size(sig_ext))/size(signal));
[ts_ext, IMU.Gyr_X, idx_interp, huecos] = rellenarHuecosInterpolacion(ts, medicion.Gyr_X, 1.6);
% signal=medicion.Gyr_X;
% sig_ext=IMU.Gyr_X;
% Calidad(4)=100*(1-(-size(signal)+size(sig_ext))/size(signal));
[ts_ext, IMU.Gyr_Y, idx_interp, huecos] = rellenarHuecosInterpolacion(ts, medicion.Gyr_Y, 1.6);
% signal=medicion.Gyr_Y;
% sig_ext=IMU.Gyr_Y;
% Calidad(5)=100*(1-(-size(signal)+size(sig_ext))/size(signal));
[ts_ext, IMU.Gyr_Z, idx_interp, huecos] = rellenarHuecosInterpolacion(ts, medicion.Gyr_Z, 1.6);
% signal=medicion.Gyr_Z;
% sig_ext=IMU.Gyr_Z;
% Calidad(6)=100*(1-(-size(signal)+size(sig_ext))/size(signal));
[ts_ext, IMU.Mag_X, idx_interp, huecos] = rellenarHuecosInterpolacion(ts, medicion.Mag_X, 1.6);
% signal=medicion.Mag_X;
% sig_ext=IMU.Mag_X;
% Calidad(7)=100*(1-(-size(signal)+size(sig_ext))/size(signal));
[ts_ext, IMU.Mag_Y, idx_interp, huecos] = rellenarHuecosInterpolacion(ts, medicion.Mag_Y, 1.6);
% signal=medicion.Mag_Y;
% sig_ext=IMU.Mag_Y;
% Calidad(8)=100*(1-(-size(signal)+size(sig_ext))/size(signal));
[ts_ext, IMU.Mag_Z, idx_interp, huecos] = rellenarHuecosInterpolacion(ts, medicion.Mag_Z, 1.6);

%% testigo del numero de muestras interpoladas:
%
signal=medicion.Mag_Z;
sig_ext=IMU.Mag_Z;
Calidad=100*(1-(-size(signal)+size(sig_ext))/size(signal));
disp('Calidad (% de señal no interpolada):');
disp(Calidad)

%% completar los campus del IMU std que no tiene el shimmer:
%
% Timestamp en ms:
IMU.Timestamp=ts_ext;

% Conteo de paquetes
IMU.PacketCounter=(1:height(IMU.Timestamp))';

% Tabla std IMU
IMUout=struct2table(IMU);

%% Frecuencia de muestreo real.
%
frq_ms=median(diff(ts_ext));
freq=1000/frq_ms;
disp('Muestreo (Hz): ');
disp(freq)

end