function [IMUout, Calidad] = f_cargaDOT(filename, dataLines)
%IMPORTFILE Import data from a text file
%  DOT7D422CD0031CD20250510111214 = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as a
%  table.
%
%  DOT7D422CD0031CD20250510111214 = IMPORTFILE(FILE, DATALINES) reads
%  data for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  DOT7D422CD0031CD20250510111214 = importfile("/Users/juan/Documents/MATLAB/DOT7_D422CD0031CD_20250510_111214.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 12-May-2025 18:49:24

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 17);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["PacketCounter", "Timestamp", "Quat_W", "Quat_X", "Quat_Y", "Quat_Z", "Acc_X", "Acc_Y", "Acc_Z", "Gyr_X", "Gyr_Y", "Gyr_Z", "Mag_X", "Mag_Y", "Mag_Z", "Status", "VarName17"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "VarName17", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "VarName17", "EmptyFieldRule", "auto");

% Import the data
medicion = readtable(filename, opts);

% time from relative microseconds to absolute miliseconds: 
ts=(medicion.Timestamp-medicion.Timestamp(1))/1000;
medicion.Timestamp=ts;

%IMU.PacketCounter=(1:height(medicion))';

IMUout=medicion;

%% Frecuencia de muestreo real.
%
frq_ms=median(diff(ts));
freq=1000/frq_ms;
disp('Muestreo (Hz): ');
disp(freq)


end